name: Build PRs
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint:js
      - name: Build XPI
        run: |
         cd extension
         zip -r ../firefox_translations.zip *
      - uses: actions/upload-artifact@v2
        with:
          name: extension_folder
          path: extension/
