name: Build Main
on:
  push:
    branches: [ xpi ]
  schedule:
    - cron: '0 2 * * *' # Daily at 2AM UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint:js
      - name: Build
        run: npm run build
      - name: Generate artifacts
        uses: actions/upload-artifact@v1
        with:
          name: firefox_translations
          if-no-files-found: error
          path: web-ext-artifacts/
