name: Publish release on tag
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint:js
      - name: Build
        run: npm run build        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: web-ext-artifacts/firefox_translations.xpi
