name: End-to-End test of Pull Requests
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: npm install
      - run: git clone https://github.com/glandium/git-cinnabar git-cinnabar
      - run: export PATH=$PATH:$(pwd)/git-cinnabar
      - name: Run test
        run: python3 scripts/tests/e2e-tests.py
